import type { Metadata } from 'next';
import '@/styles/globals.css';

export const metadata: Metadata = {
    title: '메일바다라',
    description: 'Generated by KimCookieYa',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className={'relative'}>{children}</body>
        </html>
    );
}
