import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import '@/styles/globals.css';
import Providers from '@/app/_component/Providers';


const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
    title: '메일바다라',
    description: 'Generated by KimCookieYa',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className={inter.className}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
