export default function Home() {
    return (
        <main className={'flex justify-center'}>
            <div className={'w-full max-w-1110'}>
                <div className={'flex flex-col items-center'}>
                    <div className={'flex flex-col items-center'}>
                        <div className={'text-center text-3xl font-bold'}>
                            <p>메일바다라</p>
                        </div>
                        <div className={'text-center text-lg'}>
                            <p>Generated by KimCookieYa</p>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    );
}
