export default function Home() {
    return (
        <main className={'flex justify-center'}>
            <div className={'max-w-1110 w-full'}>
                <div className={'flex flex-col items-center'}>
                    <div className={'flex flex-col items-center'}>
                        <div className={'text-3xl font-bold text-center'}>
                            <p>메일바다라</p>
                        </div>
                        <div className={'text-lg text-center'}>
                            <p>Generated by KimCookieYa</p>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    );
}
